-- The Final Threshold - Database Schema
-- Migration 001: Initial Schema Setup

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- TABLES
-- ============================================================================

-- Referrals Table
-- Stores unique referral codes generated by users
CREATE TABLE referrals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    referral_code TEXT UNIQUE NOT NULL,
    share_channel TEXT, -- 'whatsapp', 'instagram', 'x', 'messenger', 'email', 'link', 'qr'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    user_agent TEXT,
    source_page TEXT DEFAULT 'landing',
    
    -- Indexes
    CONSTRAINT referral_code_format CHECK (LENGTH(referral_code) >= 6)
);

CREATE INDEX idx_referrals_code ON referrals(referral_code);
CREATE INDEX idx_referrals_created_at ON referrals(created_at DESC);

-- Clicks Table
-- Logs every click on referral links
CREATE TABLE clicks (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    referral_id UUID REFERENCES referrals(id) ON DELETE CASCADE,
    utm_source TEXT,
    utm_medium TEXT,
    utm_campaign TEXT,
    device_type TEXT, -- 'mobile', 'desktop', 'tablet'
    ip_hash TEXT, -- Hashed IP for privacy
    country_code TEXT, -- 2-letter country code
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Page context
    landing_page BOOLEAN DEFAULT TRUE,
    converted BOOLEAN DEFAULT FALSE -- Did they click "Get the Book"?
);

CREATE INDEX idx_clicks_referral_id ON clicks(referral_id);
CREATE INDEX idx_clicks_created_at ON clicks(created_at DESC);
CREATE INDEX idx_clicks_converted ON clicks(converted) WHERE converted = TRUE;

-- Conversions Table
-- Tracks when users click the Amazon CTA
CREATE TABLE conversions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    click_id UUID REFERENCES clicks(id) ON DELETE CASCADE,
    referral_id UUID REFERENCES referrals(id) ON DELETE SET NULL,
    amazon_url TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_conversions_referral_id ON conversions(referral_id);
CREATE INDEX idx_conversions_created_at ON conversions(created_at DESC);

-- Email Signups Table
-- Optional newsletter/launch updates
CREATE TABLE email_signups (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    referral_id UUID REFERENCES referrals(id) ON DELETE SET NULL,
    subscribed BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')
);

CREATE INDEX idx_email_signups_email ON email_signups(email);
CREATE INDEX idx_email_signups_created_at ON email_signups(created_at DESC);

-- Settings Table
-- App configuration (Amazon URLs, AB testing, etc.)
CREATE TABLE settings (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    key TEXT UNIQUE NOT NULL,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default settings
INSERT INTO settings (key, value) VALUES
    ('amazon_urls', '{"paperback": "https://www.amazon.com/dp/B0DWLJ485W", "kindle": "https://www.amazon.com/dp/B0DWFRKLMZ"}'),
    ('ab_test_enabled', 'false'),
    ('cta_text', '"Enter the Threshold"'),
    ('share_message', '"I just discovered The Final Threshold - a dystopian journey you need to experience. Check it out:"'),
    ('analytics_enabled', 'true');

-- Admin Users Table (optional - for dashboard access)
CREATE TABLE admin_users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Function to generate unique referral code
CREATE OR REPLACE FUNCTION generate_referral_code()
RETURNS TEXT AS $$
DECLARE
    chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; -- Removed ambiguous chars
    result TEXT := '';
    i INTEGER;
BEGIN
    FOR i IN 1..8 LOOP
        result := result || substr(chars, floor(random() * length(chars) + 1)::int, 1);
    END LOOP;
    RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Function to hash IP addresses (privacy)
CREATE OR REPLACE FUNCTION hash_ip(ip_address TEXT)
RETURNS TEXT AS $$
BEGIN
    RETURN encode(digest(ip_address || 'salt_secret_key', 'sha256'), 'hex');
END;
$$ LANGUAGE plpgsql;

-- Function to get device type from user agent
CREATE OR REPLACE FUNCTION get_device_type(user_agent TEXT)
RETURNS TEXT AS $$
BEGIN
    IF user_agent ILIKE '%mobile%' OR user_agent ILIKE '%android%' OR user_agent ILIKE '%iphone%' THEN
        RETURN 'mobile';
    ELSIF user_agent ILIKE '%tablet%' OR user_agent ILIKE '%ipad%' THEN
        RETURN 'tablet';
    ELSE
        RETURN 'desktop';
    END IF;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- VIEWS (for analytics)
-- ============================================================================

-- Referral Performance View
CREATE OR REPLACE VIEW referral_performance AS
SELECT 
    r.id,
    r.referral_code,
    r.share_channel,
    r.created_at,
    COUNT(DISTINCT c.id) as total_clicks,
    COUNT(DISTINCT CASE WHEN c.converted = TRUE THEN c.id END) as conversions,
    CASE 
        WHEN COUNT(DISTINCT c.id) > 0 
        THEN ROUND((COUNT(DISTINCT CASE WHEN c.converted = TRUE THEN c.id END)::NUMERIC / COUNT(DISTINCT c.id)::NUMERIC) * 100, 2)
        ELSE 0 
    END as conversion_rate
FROM referrals r
LEFT JOIN clicks c ON r.id = c.referral_id
GROUP BY r.id, r.referral_code, r.share_channel, r.created_at;

-- Daily Stats View
CREATE OR REPLACE VIEW daily_stats AS
SELECT 
    DATE(created_at) as date,
    COUNT(*) as total_clicks,
    COUNT(DISTINCT referral_id) as unique_referrals,
    COUNT(CASE WHEN converted = TRUE THEN 1 END) as conversions,
    COUNT(CASE WHEN device_type = 'mobile' THEN 1 END) as mobile_clicks,
    COUNT(CASE WHEN device_type = 'desktop' THEN 1 END) as desktop_clicks
FROM clicks
GROUP BY DATE(created_at)
ORDER BY DATE(created_at) DESC;

-- Top Referrers View
CREATE OR REPLACE VIEW top_referrers AS
SELECT 
    r.referral_code,
    r.share_channel,
    COUNT(DISTINCT c.id) as total_clicks,
    COUNT(DISTINCT CASE WHEN c.converted = TRUE THEN c.id END) as conversions,
    r.created_at
FROM referrals r
LEFT JOIN clicks c ON r.id = c.referral_id
GROUP BY r.id, r.referral_code, r.share_channel, r.created_at
HAVING COUNT(DISTINCT c.id) > 0
ORDER BY total_clicks DESC
LIMIT 100;

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE clicks ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversions ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_signups ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- Public can insert referrals and clicks (for tracking)
CREATE POLICY "Anyone can create referrals" ON referrals
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Anyone can view referrals" ON referrals
    FOR SELECT USING (true);

CREATE POLICY "Anyone can create clicks" ON clicks
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Anyone can create conversions" ON conversions
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Anyone can signup for email" ON email_signups
    FOR INSERT WITH CHECK (true);

-- Only authenticated admins can view analytics
CREATE POLICY "Admins can view all clicks" ON clicks
    FOR SELECT USING (
        auth.uid() IN (SELECT id FROM admin_users WHERE email = auth.email())
    );

CREATE POLICY "Admins can view all conversions" ON conversions
    FOR SELECT USING (
        auth.uid() IN (SELECT id FROM admin_users WHERE email = auth.email())
    );

CREATE POLICY "Admins can view email signups" ON email_signups
    FOR SELECT USING (
        auth.uid() IN (SELECT id FROM admin_users WHERE email = auth.email())
    );

-- Settings are readable by all, writable by admins only
CREATE POLICY "Anyone can read settings" ON settings
    FOR SELECT USING (true);

CREATE POLICY "Admins can update settings" ON settings
    FOR UPDATE USING (
        auth.uid() IN (SELECT id FROM admin_users WHERE email = auth.email())
    );

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Auto-update timestamp on settings
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_settings_updated_at
    BEFORE UPDATE ON settings
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- COMMENTS (Documentation)
-- ============================================================================

COMMENT ON TABLE referrals IS 'Stores unique referral codes generated when users share the book';
COMMENT ON TABLE clicks IS 'Logs every click on referral links for analytics';
COMMENT ON TABLE conversions IS 'Tracks when users click the Amazon CTA button';
COMMENT ON TABLE email_signups IS 'Newsletter/launch update email list';
COMMENT ON TABLE settings IS 'App configuration and feature flags';
COMMENT ON TABLE admin_users IS 'Authorized users who can access the analytics dashboard';

COMMENT ON COLUMN clicks.ip_hash IS 'SHA-256 hashed IP address for privacy compliance';
COMMENT ON COLUMN clicks.converted IS 'True if user clicked the Amazon CTA from this visit';
